version: '3'

services:
    miaoma-docs-postgresql:
        image: bitnami/postgresql:latest
        container_name: miaoma-docs-postgresql
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=postgres
            - ALLOW_EMPTY_PASSWORD=yes
            - POSTGRESQL_DATABASE=postgres
        volumes:
            - ./postgresql_data:/bitnami/postgresql

networks:
    default:
        name: miaoma-docs-network
        driver: bridge
